---
apiVersion: v1
kind: ConfigMap

metadata:
  name: oficina360-config
  namespace: oficina360
  labels:
    app.kubernetes.io/name: oficina360
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: oficina360

data:
  SPRING_PROFILES_ACTIVE: "docker"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "oficina360"
  JWT_ISSUER: "oficina360"