---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pvc
  namespace: oficina360
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: oficina360

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi