---
apiVersion: v1
kind: Secret

metadata:
  name: oficina360-secret
  namespace: oficina360

type: Opaque

stringData:
  DB_USERNAME: "SUBSTITUIR_USUARIO"
  DB_PASSWORD: "SUBSTITUIR_SENHA"
  JWT_SECRET: "SUBSTITUIR_CHAVE_JWT