workspace {

    model {

        atendimento = softwareSystem "Domínio Oficina360" {

            # Criamos o container que vai abrigar os componentes
            apiAtendimento = container "API de Atendimento" "Backend do sistema Oficina360" "Java / Spring Boot" {

                cliente = component "Cliente"
                veiculo = component "Veículo"
                os = component "OrdemServico"

                servico = component "Servico"

                estoque = component "Estoque"

                itemEstoque = component "OrdemServicoItemEstoque"

                tempoExecucao = component "TempoExecucaoServico"

                usuario = component "Usuario"

                cliente -> veiculo
                cliente -> os

                os -> servico
                os -> itemEstoque

                servico -> tempoExecucao
            }
        }

    }

    views {

        # Ajustamos a visão para apontar para o container correto
        component apiAtendimento {
            include *
            autolayout lr
        }

    }

}
