name: Security Scan (Snyk)

on: [push, pull_request]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Instala o Java/Maven se o seu projeto precisar construir a árvore de dependências
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Varredura de Dependências do Maven (SCA)
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Varredura do seu Código Próprio (SAST) - Opcional
      - name: Run Snyk Code to check for code issues
        uses: snyk/actions/code@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

