name: Security Scan (Snyk)

on: [push, pull_request]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master

      - name: Snyk Open Source Test (Maven)
        run: snyk test --maven
