name: CI/CD

on:
  push:
    branches:
      - main
      - master
      - develop

  pull_request:

env:
  JAVA_VERSION: '21'
  IMAGE_NAME: oficina360

jobs:
#todo descobrir como utilizar cache
#  # ============================================================
#  # 1. SECURITY
#  # ============================================================
#  security:
#    name: OWASP Dependency Check
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Setup Java
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: ${{ env.JAVA_VERSION }}
#          cache: maven
#
#      - name: Cache OWASP data
#        uses: actions/cache@v4
#        with:
#          path: ~/.m2/dependency-check-data
#          key: ${{ runner.os }}-owasp-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-owasp-
#
#      - name: OWASP Dependency Check
#        run: mvn dependency-check:check
#        env:
#          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}


  # ============================================================
  # 2. BUILD + TEST + COVERAGE
  # ============================================================
  test:
    name: Build, Tests and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build and test
        run: mvn clean verify

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: oficina360-jar
          path: target/*.jar

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: docs/security/jacoco/


  # ============================================================
  # 3. SONARCLOUD
  # ============================================================
  sonar:
    name: SonarCloud
    needs:
      - security
      - test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Download JaCoCo report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: docs/security/jacoco

      - name: SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=michaelhion_tech_challenge_pos_arquitetura_de_software \
            -Dsonar.organization=michaelhion \
            -Dsonar.host.url=https://sonarcloud.io


  # ============================================================
  # 4. DOCKER
  # ============================================================
  docker:
    name: Build and Push Docker Image
    needs: sonar

    # Só publica imagem quando for push
    # Não publica em Pull Request
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: oficina360-jar
          path: target

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest


#  # ============================================================
#  # 5. DEPLOY KUBERNETES
#  # ============================================================
#  deploy:
#    name: Deploy to Kubernetes
#    needs: docker
#
#    # Deploy somente na main
#    if: github.ref == 'refs/heads/main'
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Setup kubectl
#        uses: azure/setup-kubectl@v4
#
#      - name: Configure Kubernetes
#        run: |
#          mkdir -p ~/.kube
#          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
#
#      - name: Check Kubernetes connection
#        run: |
#          kubectl cluster-info
#          kubectl get nodes
#
#      # --------------------------------------------------------
#      # Database
#      # --------------------------------------------------------
#      - name: Deploy database
#        run: |
#          kubectl apply -f k8s/database/
#
#      - name: Wait for PostgreSQL
#        run: |
#          kubectl rollout status \
#            deployment/postgres \
#            --timeout=180s
#
#      # --------------------------------------------------------
#      # Application
#      # --------------------------------------------------------
#      - name: Apply application manifests
#        run: |
#          kubectl apply -f k8s/app/
#
#      # --------------------------------------------------------
#      # Update image
#      # --------------------------------------------------------
#      - name: Update application image
#        run: |
#          kubectl set image deployment/oficina360 \
#            oficina360=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
#
#      # --------------------------------------------------------
#      # Wait for deployment
#      # --------------------------------------------------------
#      - name: Wait for application rollout
#        run: |
#          kubectl rollout status \
#            deployment/oficina360 \
#            --timeout=180s
#
#      - name: Check application pods
#        run: |
#          kubectl get pods
#          kubectl get services